title: Ethan's Page
author: Ethan Knapp
email: ethanknapp1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site will hopefully be really cool one day later this year.
# social links
twitter_username: @knappethan
github_username:  @ethanknapp

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
